default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root # Or your MySQL username
  password: <%= ENV['MYSQL_PASSWORD'] %> # It's good practice to use environment variables for sensitive information
  host: localhost

development:
  <<: *default
  database: boxdega

test:
  <<: *default
  database: boxdega_test

production:
  <<: *default
  database: boxdega_production
  username: myapp
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] || 'localhost' %>